org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false
minecraft_version=1.19.2
minecraft_version_range=[1.19.2, 1.19.3)
forge_version=43.2.14
forge_version_range=[43,)
loader_version_range=[43,)
mapping_channel=parchment
mapping_version=2022.08.14-1.19.2
mod_id=nffgirls
archive_base_name=nffgirls-1.19.2
mod_name=NFF: Girls
mod_license=LGPL-3.0
mod_group_id=net.sodiumzh.nff.girls
mod_authors=SodiumZH
mod_description=Enjoy your Minecraft days with monster girls!

mixinextras_version=0.3.1
mixinextras_min_version=0.3.0

mod_version=0.1.32.1
filename_version=0.1.32.1
nfu_version=0.1.32
nfu_version_range=[0.1.32, 0.1.33)
services_version=0.1.32
services_version_range=[0.1.32, 0.1.33)
hmag_version_range=[6.2.19, 7.0)
jei_version=11.6.0.1015
jei_version_range=[11,12)
patchouli_version=77
patchouli_version_range=[1.19.2-76,)
